create table passport.person
(
    id   int primary key generated by default as identity,
    name varchar(100) not null,
    age  int

);
create table passport.passport
(
    id              int primary key generated by default as identity,
    passport_number int not null,
    person_id       int unique references passport.person (id) on delete cascade
);
